from naddeoa/booty:ubuntu22.04

COPY ./ssh ./.ssh
RUN sudo chown -R myuser:myuser ./.ssh
RUN chmod 600 .ssh/id_rsa

COPY ./examples/install.booty ./
COPY ./dist/booty_linux_x86_64 ./

ENV PATH="/home/myuser/.local/bin:${PATH}"

RUN ./booty_linux_x86_64 -i -y

CMD ["fish"]
