from naddeoa/booty:ubuntu22.04

RUN sudo apt-get update




COPY ./ssh ./.ssh
RUN sudo chown -R myuser:myuser ./.ssh
RUN chmod 600 .ssh/id_rsa

COPY ./examples/install.booty ./
COPY ./dist/booty_linux_x86_64 ./



RUN ./booty_linux_x86_64 -i -y --no-sudo

CMD ["bash"]
