name: Build CI

on:
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.11.6"

      - uses: Gr1N/setup-poetry@v8
        name: Install poetry
        with:
          poetry-version: 1.7.1

      - name: Install python dependencies
        run: poetry install

      - name: Building
        run: make build build-binary-linux

      - name: Check types
        run: make lint

      - name: Check formatting
        run: make format

      # Buiding the container is basically the integ test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Import SSH Config
        run: |
          mkdir ./ssh/
          echo "${{ secrets.DOCKER_PRIVATE_SSH_KEY }}" > ./ssh/id_rsa
          echo "${{ secrets.DOCKER_KNOWN_HOSTS }}" > ./ssh/known_hosts

      - name: Build main Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          push: false
          tags: booty/test${{ github.sha }}

      # The build host is running out of disk space
      - name: Delete docker images and cache
        shell: bash
        run: docker system prune -a -f

